---
- name: Testing andrewrothstein.func_e (default)
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
- name: Testing andrewrothstein.func_e
  hosts: all
  vars:
    func_e_envoy_install:
      - version: 1.21.1
      - version: 1.33.0
    func_e_envoy_link:
      version: 1.33.0
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'envoy --version'
      ansible.builtin.command: envoy --version
      changed_when: false
      register: func_e_test_output
    - name: Output of 'envoy --version'
      ansible.builtin.debug:
        msg: '{{ func_e_test_output.stdout }}'
