---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install in {{ func_e_exe }}
  ansible.builtin.stat:
    path: '{{ func_e_exe }}'
  register: func_e_binary
  changed_when: false
- name: Downloading and installing func_e
  when: not func_e_binary.stat.exists
  block:
    - name: Mkdir {{ func_e_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ func_e_install_dir }}'
        state: directory
        mode: '755'
    - name: Downloading {{ func_e_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ func_e_url }}'
        dest: '{{ func_e_tmp_archive }}'
        mode: '644'
        checksum: '{{ func_e_checksum }}'
    - name: Unarchive {{ func_e_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        src: '{{ func_e_tmp_archive }}'
        dest: '{{ func_e_install_dir }}'
        creates: '{{ func_e_exe }}'
  always:
    - name: Rm -f {{ func_e_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ func_e_tmp_archive }}'
        state: absent

- name: Linking {{ func_e_link }} to {{ func_e_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ func_e_exe }}'
    dest: '{{ func_e_link }}'
    state: link

- name: Installing envoy proxies...
  when: func_e_envoy_install is defined
  block:
    - name: Mkdir {{ func_e_envoys_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ func_e_envoys_dir }}'
        state: directory
        mode: '755'
    - name: Installing envoy proxy distributions...
      become: true
      become_user: root
      with_items: '{{ func_e_envoy_install }}'
      ansible.builtin.command: '{{ func_e_exe }} --home-dir {{ func_e_envoys_dir }} use {{ item.version }}'
      args:
        creates: '{{ func_e_envoys_dir }}/versions/{{ item.version }}/bin/envoy'
    - name: Chmod 755 {{ func_e_envoys_dir }}/versions
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ func_e_envoys_dir }}/versions'
        state: directory
        mode: '755'
    - name: Chmod 755 {{ func_e_envoys_dir }}/versions installs
      become: true
      become_user: root
      with_items: '{{ func_e_envoy_install }}'
      ansible.builtin.file:
        path: '{{ func_e_envoys_dir }}/versions/{{ item.version }}'
        state: directory
        mode: '755'
- name: Linking envoy...
  when: func_e_envoy_link is defined
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ func_e_envoys_dir }}/versions/{{ func_e_envoy_link.version }}/bin/envoy'
    dest: '{{ func_e_parent_install_dir }}/bin/envoy'
    state: link
